# Data Exploration and Visualization

**Name:** Add your name  
**Due:** Module 6

## Purpose
Develop four findings that could help CCM attract students to computing classes. Use the two cleaned survey CSV files from Part 1. Complete every TODO; write your own analysis and explanations.

## Before you begin
Copy majors_survey_cleaned.csv and nonmajors_survey_cleaned.csv into the data folder. Open the repository folder in VS Code and select your Python kernel. Do not overwrite the cleaned files during analysis.

In [11]:
# Import tools for working with tables and charts.
import pandas as pd
import matplotlib.pyplot as plt

In [13]:
# Read the cleaned computing majors survey.
majors_cleaned = pd.read_csv("data/majors_survey_cleaned.csv")

# Read the cleaned nonmajors survey.
nonmajors_cleaned = pd.read_csv("data/non_majors_survey_cleaned.csv")

In [15]:
# Preview the majors survey.
majors_cleaned.head()

,which_course_are_you_enrolled_in?,how_did_you_hear_about_ccm?_(ccm_website),how_did_you_hear_about_ccm?_(social_media),how_did_you_hear_about_ccm?_(community_event),how_did_you_hear_about_ccm?_(family_member/friend),how_did_you_hear_about_ccm?_(current_ccm_student),how_did_you_hear_about_ccm?_(ccm_alumni),how_did_you_hear_about_ccm?_(high_school_teacher),how_did_you_hear_about_ccm?_(high_scchool_counselor),how_did_you_hear_about_ccm?_(in-app_advertisement),...,did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[employer],did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_workforce_development],did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[nj_workforce_development_program],did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[other],"was_a_computing_major/certificate_your_first_choice,_or_did_you_change_majors_from_a_different_ccm_program?_if_you_changed_majors,_indicate_what_your_first_major_was.","on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_in_taking_more_computing_classes?",please_explain_your_answer_to_the_question_above.__why_or_why_not_would_you_be_interested_in_taking_another_computing_class?,gender,race/ethnicity,age
0,CMP 130 Intro to IT,No,No,No,Yes,No,No,Yes,Yes,No,...,No,No,No,No,First Choice,NaN,NaN,Man,White/Caucasian,18 and younger
1,CMP 130 Intro to IT,No,No,Yes,Yes,No,Yes,No,No,No,...,No,Yes,Yes,Don't recall,Criminal Sceince,NaN,NaN,Man,White/Caucasian,35-64
2,CMP 130 Intro to IT,Yes,No,Yes,Yes,No,No,Yes,Yes,No,...,Don't recall,Don't recall,Don't recall,Don't recall,First Choice,NaN,NaN,Man,Multi-Racial,18 and younger
3,CMP 130 Intro to IT,No,No,No,Yes,Yes,No,No,No,No,...,No,No,No,No,Engineering,NaN,NaN,Man,Hispanic or Latino,21-24
4,CMP 130 Intro to IT,No,No,No,Yes,No,No,No,No,No,...,No,No,No,No,First Choice,NaN,NaN,Man,White/Caucasian,19-20

In [19]:
# Preview the nonmajors survey.
nonmajors_cleaned.head()

,which_course_are_you_currently_enrolled_in?,why_take_a_computing_class_at_ccm?_[required_for_my_degree],why_take_a_computing_class_at_ccm?_[to_keep_current_in_compting_skills],why_take_a_computing_class_at_ccm?_[career_advancemnt],why_take_a_computing_class_at_ccm?_[career_change],why_take_a_computing_class_at_ccm?_[professional_development],why_take_a_computing_class_at_ccm?_[job_displacement],why_take_a_computing_class_at_ccm?_[relocation],why_take_a_computing_class_at_ccm?_[it_industry_certification],why_take_a_computing_class_at_ccm?_[financial],...,"if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[cybersecurity]","if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[app_development]","if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[data_analytics]","if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[machine_learning/artificial_intelligence]",which_computing_classes_interest_you_most?_[computer_programming],"if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[game_design]","if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[hardware_installation_&_repair]",gender,race/ethnicity,age
0,CMP 126 Computer Technology and Applications,Yes,No,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,Woman,White/Caucasian,18 and younger
1,CMP 126 Computer Technology and Applications,Yes,No,No,No,No,No,No,No,No,...,No,No,No,No,No,Yes,No,Non-binary,Choose not to reply,18 and younger
2,CMP 126 Computer Technology and Applications,Yes,Yes,No,No,Yes,No,No,No,No,...,Yes,No,Yes,No,No,No,No,Woman,Asian,19-20
3,CMP 135 Computer Concepts with Applications,Yes,No,No,No,No,No,No,No,No,...,Yes,No,No,No,No,Yes,No,Woman,Hispanic or Latino,21-24
4,CMP 135 Computer Concepts with Applications,Yes,No,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,Man,White/Caucasian,18 and younger

## Inspect before choosing questions
Check the column names, row counts, data types, and missing values in each survey. The surveys may have different columns. Use the exact names in your own files.

In [ ]:
# TODO: Display the column names and dimensions of each survey.
# TODO: Inspect data types and missing values relevant to your analysis.

## Your analysis plan
**TODO:** Briefly describe the recruitment problem and list four different questions you plan to investigate. Choose questions that the available data can answer.

For each finding below, use pandas to prepare the evidence and Matplotlib to create a useful chart. A bar chart compares categories; a histogram groups numeric values into ranges; a scatter plot compares paired numeric values; a pie chart shows a few shares of one total. Choose based on the question, not to use every chart type.

## Finding 1

**Question — TODO:** State one question about student interests, recruitment, or communication.

**Plan — TODO:** Identify the survey, columns, and groups you will use. Explain which chart fits and why.

In [ ]:
# TODO: Select the relevant data and check missing responses.
# TODO: Calculate counts, percentages, or another useful summary.
# TODO: Display the evidence and include group sizes when comparing groups.

In [ ]:
# TODO: Start a new figure and draw a chart from your analysis.
# TODO: Add a clear title and axis labels when applicable.
# TODO: Display the chart.

**Evidence — TODO:** Explain what your output and chart show. Include actual numbers. If using percentages, state the total used.

**Recommendation — TODO:** Explain one action CCM could consider based on this evidence. Describe why the finding supports the action.

## Finding 2

**Question — TODO:** State one question about student interests, recruitment, or communication.

**Plan — TODO:** Identify the survey, columns, and groups you will use. Explain which chart fits and why.

In [ ]:
# TODO: Select the relevant data and check missing responses.
# TODO: Calculate counts, percentages, or another useful summary.
# TODO: Display the evidence and include group sizes when comparing groups.

In [ ]:
# TODO: Start a new figure and draw a chart from your analysis.
# TODO: Add a clear title and axis labels when applicable.
# TODO: Display the chart.

**Evidence — TODO:** Explain what your output and chart show. Include actual numbers. If using percentages, state the total used.

**Recommendation — TODO:** Explain one action CCM could consider based on this evidence. Describe why the finding supports the action.

## Finding 3

**Question — TODO:** State one question about student interests, recruitment, or communication.

**Plan — TODO:** Identify the survey, columns, and groups you will use. Explain which chart fits and why.

In [ ]:
# TODO: Select the relevant data and check missing responses.
# TODO: Calculate counts, percentages, or another useful summary.
# TODO: Display the evidence and include group sizes when comparing groups.

In [ ]:
# TODO: Start a new figure and draw a chart from your analysis.
# TODO: Add a clear title and axis labels when applicable.
# TODO: Display the chart.

**Evidence — TODO:** Explain what your output and chart show. Include actual numbers. If using percentages, state the total used.

**Recommendation — TODO:** Explain one action CCM could consider based on this evidence. Describe why the finding supports the action.

## Finding 4

**Question — TODO:** State one question about student interests, recruitment, or communication.

**Plan — TODO:** Identify the survey, columns, and groups you will use. Explain which chart fits and why.

In [ ]:
# TODO: Select the relevant data and check missing responses.
# TODO: Calculate counts, percentages, or another useful summary.
# TODO: Display the evidence and include group sizes when comparing groups.

In [ ]:
# TODO: Start a new figure and draw a chart from your analysis.
# TODO: Add a clear title and axis labels when applicable.
# TODO: Display the chart.

**Evidence — TODO:** Explain what your output and chart show. Include actual numbers. If using percentages, state the total used.

**Recommendation — TODO:** Explain one action CCM could consider based on this evidence. Describe why the finding supports the action.

## Final summary
**TODO:** Summarize the four findings, identify your most useful recommendation, and describe one limitation of your analysis. Distinguish survey evidence from suggestions.

## Before you submit
- Complete all TODO sections and comment your code.
- Confirm four different findings, each supported by a chart and an explanation.
- Keep the cleaned CSV files in data unchanged.
- Complete AI-Use-Report.md honestly, including if you did not use AI.
- Save, restart the kernel, and Run All. Fix errors and save again with outputs visible.
- Commit and push your notebook, AI report, and two cleaned CSV files.
- Verify the files on GitHub and submit the public repository link in Blackboard Ultra.